# Generated by Django 2.2.4 on 2019-08-17 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20180731_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mailing_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
